before_script:
  - docker info

build_image:
  script:
    - docker build --force-rm --rm -t sdongjie/node-cms .
    - docker stop cms || true && docker rm cms || true
    - docker run -p 6006:6006 --name cms -d sdongjie/node-cms